### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#5120] opened 2023-09-11 09:12 UTC
### Discussed in https://github.com/maxi-blocks/maxi-blocks/discussions/4543

<div type='discussions-op-text'>

<sup>Originally posted by **Marko64** March 14, 2023</sup>
Blocks rendering based on conditions. Example: https://academy.bricksbuilder.io/article/element-conditions/</div>

**Comment by Marko64** [comment] 2024-01-22 14:55
Duplicate of https://github.com/maxi-blocks/maxi-blocks/issues/4525

**Closed** 2024-01-22 14:57 UTC
