### ISSUE TITLE
Need to add support for CPT templates

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5587] opened 2024-05-17 10:58 UTC
### Description
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/15865079-9069-4171-a998-e8c7002726ea)
Backend:
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/eb914431-fdbf-415a-8109-a2c14035c74b)
Frontend:
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/f2b33060-48e5-4588-9796-950a29b4f980)

[acf-export-2024-05-17.json](https://github.com/maxi-blocks/maxi-blocks/files/15348013/acf-export-2024-05-17.json)

**Comment by elzadj** [comment] 2024-05-31 10:47
Looks like the issue has 2 parts - plugin fix (looks like the styles are not working?) and then adding our template to our theme. 
Let's first do the plugin fix here, and move our CPT template to the theme github https://github.com/maxi-blocks/maxiblocks-theme/issues/3

**Comment by myroslavve** [comment] 2024-06-19 17:21
Seems to be fixed on master for me @Olekrut, can you check please

**Comment by myroslavve** [comment] 2024-06-26 19:44
> @myroslavve looks like frontend is ok now, but not backend https://jam.dev/c/0c87a163-2344-4b83-8d3d-c4bb44a6e32d

Can't reproduce this

**Comment by elzadj** [comment] 2024-06-28 13:04
- [ ] 404 no route error
- [ ] Author field is missing
- [ ] Need to add ACF support for CPT

**Closed** 2024-07-08 15:30 UTC
Labels: 🌟 enhancement, 🙏 high priority, from support, 🧑‍🚒 need for theme 🧑‍🚒, 1.9.1
